version: 0.2
# variables:
#   parameter-store:
#     BUKET_NAME: git-cicd-bucket
phases:
  # install:
  #   runtime-versions:
  #     nodejs: 12
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - sam build
  post_build:
    commands:
      - sam package --template-file template.yaml --output-template-file outputSamTemplate.yaml --s3-bucket git-cicd-bucket
# artifacts:
#   type: zip
#   files:
#     - outputSamTemplate.yaml
#   discard-paths: yes
