version: 0.2
variables:
  parameter-store:
    BUKET_NAME: /CodeBuild/git-cicd-bucket
phases:
  # install:
  #   runtime-versions:
  #     nodejs: 12
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - sam package -template-file template.yaml $BUKET_NAME -output-template out.yaml
artifacts:
  type: zip
  files:
    - out.yml
  discard-paths: yes