version: 0.2
variables:
  parameter-store:
    BUKET_NAME: git-cicd-bucket
phases:
  # install:
  #   runtime-versions:
  #     nodejs: 12
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
  post_build:
    commands:
      - sam package -t template.yaml --s3-bucket $BUKET_NAME --output-template-file out.yaml
artifacts:
  type: zip
  files:
    - out.yml
  discard-paths: yes