version: 0.2

phases:
  install:
    runtime-versions:
      node: 12
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'
