AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-with-testing

  Sample SAM Template for sam-app-with-testing
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs12.x
    Handler: index.handler

Resources:

#   ################LAMBDA FUNCTIONS ########################
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: HelloWorld
      CodeUri: ./hello-world/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  NewTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./new-test-lambda
      FunctionName: new-test-lambda
      Events:
        EndPoint:
          Type: Api
          Properties:
            Path: /test-lambda
            Method: get


